crawler:
  documents:
    storage:
      account: https://[].blob.core.windows.net/
      container: container
    urls:
      - https://www.google.come/  
  html:
    striptags: true
    parser:
      ignored_classes:
        - .divFooter
        - "#divFooter"
        - .divContentBaseOptional
        - "#divContentBaseOptional"
        - .divHeader
        - "#divHeader"
        - .divSticker
        - "#divSticker"
        - .divSkyScraper
        - "#divSkyScraper"
        - .ulNavigationTop
        - "#ulNavigationTop"
        - .ulLogin
        - "#ulLogin"
        - .selectQuickNavi
        - "#selectQuickNavi"
        - .imheader
        - "#imheader"
        - .imfooter
        - "#imfooter"
        - .colNavigationLeft
        - "#colNavigationLeft"
        - .ulNavigationBreadCrumb
        - "#ulNavigationBreadCrumb"
        - .divSuperBanner
        - "#divSuperBanner"
        - .mobileFooter
        - "#mobileFooter"
        - .divSocialFooter
        - "#divSocialFooter"
        - .flyoutBox
        - "#flyoutBox"
        - .shipping-data
        - "#shipping-data"
        - .dynhubGradient
        - "#dynhubGradient"
        - .moreInfo
        - "#moreInfo"
        - .divMobileHeaderContainer
        - "#divMobileHeaderContainer"
        - .subnav
        - "#subnav"
        - .shipping
        - "#shipping"
        - .top-nav
        - "#top-nav"
        - .promobanner_lte_max
        - "#promobanner_lte_max"
        - .promobanner_eu_roaming
        - "#promobanner_eu_roaming"
        - .tariffSlide
        - "#tariffSlide"
        - .tariffBox
        - "#tariffBox"
        - .top-links
        - "#top-links"
        - .global-nav-wrap
        - "#global-nav-wrap"
        - .redSummary
        - "#redSummary"
        - .orderBox
        - "#orderBox"
        - .menuVertragstarife
        - "#menuVertragstarife"
        - .ui-link
        - "#ui-link"
        - .rhombus
        - "#rhombus"
        - .MDDsubNavItems-3
        - "#MDDsubNavItems-3"
        - .divFooterWrapper
        - "#divFooterWrapper"
        - .wrapper-fo-qualityseals
        - "#wrapper-fo-qualityseals"
        - .arrow
        - "#arrow"
        - .menu
        - "#menu"
        - .delivery
        - "#delivery"
        - .insurance
        - "#insurance"
        - .card
        - "#card"
        - .headBox
        - "#headBox"
        - .tabbedNavigationHubpage
        - "#tabbedNavigationHubpage"
        - .divTabbedNavigationDynHUB
        - "#divTabbedNavigationDynHUB"
        - .price-detail
        - "#price-detail"
        - .nsf-handy-insurance-overlay-content
        - "#nsf-handy-insurance-overlay-content"
        - .mod-footnotes
        - "#mod-footnotes"
        - .mod-glnav
        - "#mod-glnav"
        - .glnav
        - "#glnav"
        - .mod-glnav-footer
        - "#mod-glnav-footer"
        - .footer-wrapper
        - "#footer-wrapper"
        - .metaWrapper
        - "#metaWrapper"
        - .mainNavWrapper
        - "#mainNavWrapper"
        - .navigation-wrapper
        - "#navigation-wrapper"
        - .footer_content
        - "#footer_content"
        - .nav-base
        - "#nav-base"
        - .mainNav
        - "#mainNav"
        - .discovery-footer
        - "#discovery-footer"
        - .feedback-main
        - "#feedback-main"
        - .footer-container
        - "#footer-container"
        - .nav-mainLevel
        - "#nav-mainLevel"
        - .main-nav
        - "#main-nav"
        - .footer--no-margin
        - "#footer--no-margin"
        - .About-product
        - "#About-product"
        - .About-brand
        - "#About-brand"
  logs:
    storage:
      account: https://[].blob.core.windows.net/
      container: containerlogs
